---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by wakfu.
--- DateTime: 2020/5/25 19:10
---
local json = require("json")

function test()
    local ini2 = require 'ini2'
    local ini3 = require 'ini3'

    local settings2 = ini2.load("lxconfig.ini")
    local settings3 = ini3.load("lxconfig.ini")

    --settings2["CLENT0"].user = "问题"
    --ini2.save("lxconfig.ini", settings2)

    print("settings2类型：", type(settings2))
    print(json.encode(settings2))

    print("settings3类型：", type(settings3))
    print(json.encode(settings3))

    --local line = "proxyserver="
    --local param, value = line:match('^([%w|_]+)%s-=%s-(.*)$');
    --print(param, value)

end

function test1()
    local data = {}
    data["CLENT1"] = {
        date = 81,
    }
    data["CLENT0"] = {
        date = 80,
    }

    for section, param in pairs(data) do
        print(section)
    end
end
function test2()
    local list = { "we", "as" }
    local lis2 = list;
    print(json.encode(lis2))
    table.insert(list, 1, { m = "" })
    print(json.encode(list))
    print(json.encode(lis2))
end

---@param range number
function taxRate(range, invest, taxRate)
    local function rangeCount(newInvest, count)
        newInvest = (1 + taxRate) * newInvest
        return newInvest
    end

    local count = 0;
    local i = 0;
    repeat
        i = i + 1;
        count = rangeCount(count + invest)
        print("第" .. i .. "期", count)
    until i == range

    return count
end

local year = 1
print("count:", taxRate(3 * year, 50, 0.1))
print(3* year * 50)
--test2()
--test()
--test1()

