---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by wakfu.
--- DateTime: 2020/5/25 19:10
---


function test()
    local json = require("json")
    local ini2 = require 'ini2'
    local ini3 = require 'ini3'

    local settings2 = ini2.load("lxconfig.ini")
    local settings3 = ini3.load("lxconfig.ini")

    --settings2["CLENT0"].user = "问题"
    --ini2.save("lxconfig.ini", settings2)

    print("settings2类型：", type(settings2))
    print(json.encode(settings2))

    print("settings3类型：", type(settings3))
    print(json.encode(settings3))

    --local line = "proxyserver="
    --local param, value = line:match('^([%w|_]+)%s-=%s-(.*)$');
    --print(param, value)

end

function test1()
    local data = {}
    data["CLENT1"] = {
        date = 81,
    }
    data["CLENT0"] = {
        date = 80,
    }

    for section, param in pairs(data) do
        print(section)
    end
end
test()
--test1()
